[mypy]
show_error_codes = True

[mypy-TinyLensGpu.*]
disable_error_code = import-untyped

[mypy-caskade]
ignore_missing_imports = True
disable_error_code = import-untyped

[mypy-caskade.*]
ignore_missing_imports = True
disable_error_code = import-untyped
