dataset:
  data_path: "data/image.fits"
  noise_path: "data/noise.fits"
  psf_path: "data/psf.fits"
  pixel_scale: 0.074

model_components:
  lens_mass_list: []

  source_light_list: []

  lens_light_list:
    - type: "Sersic"
      params:
        R_sersic:
          prior_type: "uniform"
          prior_settings: [0.001, 2.001]
          limits: [0.0001, 2.0]
          fixed: false
        n_sersic:
          prior_type: "gaussian"
          prior_settings: [4.0, 0.5]
          limits: [0.3, 6.0]
          fixed: false
        e1:
          prior_type: "gaussian"
          prior_settings: [0.0, 0.3]
          limits: [-1.0, 1.0]
          fixed: false
        e2:
          prior_type: "gaussian"
          prior_settings: [0.0, 0.3]
          limits: [-1.0, 1.0]
          fixed: false
        center_x:
          fixed: true
          fixed_value: 0.0
        center_y:
          fixed: true
          fixed_value: 0.0
        Ie:
          use_linear: true

inference:
  type: "optimizer"
  method: "differential_evolution"
  settings:
    strategy: "best1bin"
    maxiter: 1000
    popsize: 15
    tol: 0.01
    mutation: [0.5, 1.0]
    recombination: 0.7
    seed: 42
    polish: true
    init: "latinhypercube"
    atol: 0
    updating: "immediate"

output:
  path: "output"
  figures:
    results: "model_results.png"
  tables:
    summary: "result_summary.csv"
  datasets:
    subplot: "dataset_subplot.png" 