dataset:
  data_path: data/image.fits
  noise_path: data/noise.fits
  psf_path: data/psf.fits
  pixel_scale: 0.074
model_components:
  lens_mass_list: []
  source_light_list: []
  lens_light_list:
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.01
      center_x:
        fixed: false
        prior_type: gaussian
        prior_settings:
        - 0.0
        - 0.1
        limits:
        - -3.0
        - 3.0
      center_y:
        fixed: false
        prior_type: gaussian
        prior_settings:
        - 0.0
        - 0.1
        limits:
        - -3.0
        - 3.0
      e1:
        fixed: false
        prior_type: gaussian
        prior_settings:
        - 0.0
        - 0.3
        limits:
        - -1.0
        - 1.0
      e2:
        fixed: false
        prior_type: gaussian
        prior_settings:
        - 0.0
        - 0.3
        limits:
        - -1.0
        - 1.0
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.015029247363536643
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.022587827631437313
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.03394780488777995
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.05102099571075232
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.07668071652708387
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.11524534566987764
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.17320508075688776
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.2603142003316607
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.39123265090257603
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.5879932287106993
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 0.883709568237768
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 1.3281489698569586
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 1.9961079403606603
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
  - type: Gaussian
    params:
      sigma:
        fixed: true
        fixed_value: 3.0
      center_x:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_x
      center_y:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: center_y
      e1:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e1
      e2:
        fixed: true
        fixed_value:
          component_type: lens_light_list
          component_idx: 0
          parameter: e2
      flux:
        use_linear: true
inference:
  type: sampler
  method: nautilus
  settings:
    nlive: 200
    batch_size: 200
output:
  path: output
  figures:
    results: model_results.png
    corner: model_corner.png
  tables:
    samples: result_samples.csv
    summary: result_summary.csv
  datasets:
    subplot: dataset_subplot.png
solver_type: nnls
